Calendar/urls.py
from django.urls import path, include
from . import views



app_name = 'Calendar'
urlpatterns = [
    
    path('home/', views.home, name = "home"),
    path('calendarprev/', views.calendarprev, name = "calendprev"),    
    path('calendarnext/', views.calendarnext, name = "calendnext"),
    path('calendar/', views.calendar, name = "calend"),
    path('calendar/<slug>/', views.session_list, name = "connect"),
    path('calendar/<slug>/<slugb>/', views.exercise_list, name = 'vecro'),
   
]

PlanAppProject4/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Calendar.urls")),
    path('login/', include("login.urls")),
    path('', include('pwa.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),      
]

urlpatterns += staticfiles_urlpatterns() 

login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'
urlpatterns = [  
    path('signup/', views.signup_view, name = 'signup'),
    path('signin/', views.signin_view, name = 'signin'),
    path('logout/', views.logout_view, name = 'logout'),
 
]

Calendar/forms.py
from django import forms
from . import models


class SaveData(forms.ModelForm):
    class Meta:
        model = models.Z_Data
        fields = ['hold1','rep1','weight1','dist1','note1',
                  'hold2','rep2','weight2','dist2','note2',
                  'hold3','rep3','weight3','dist3','note3',
                  'hold4','rep4','weight4','dist4','note4',                  
                  'hold5','rep5','weight5','dist5','note5',
                  'hold6','rep6','weight6','dist6','note6',
                  'hold7','rep7','weight7','dist7','note7',
                  'hold8','rep8','weight8','dist8','note8',
                  'hold9','rep9','weight9','dist9','note9',
                  'hold10','rep10','weight10','dist10','note10',                  
                  'hold11','rep11','weight11','dist11','note11',
                  'hold12','rep12','weight12','dist12','note12',   
                  ]
  
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

Calendar/views.py
from django.shortcuts import render
from .models import *
from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth import authenticate
from dateutil.relativedelta import relativedelta
from . import forms
from django.contrib import messages

click = 0
varislug = 0
varislug2 = 0
varislug3 = 0
planoftheday = 0


def home(request):
    return render(request, 'calentemp/home.html')

def calendarnext(request):
    global click
    click = click+1
    now = datetime.today()+ relativedelta(months=click)
    today = now.strftime("Y%m_%Y")
    u = request.user
    today2 = datetime.today()
    today3 = int(today2.strftime("%d"))
    clickmois = click
    
    
    if(today=="Y01_2020"):
        Today = A_2020_January
    elif(today=="Y02_2020"):
        Today = B_2020_February
    elif(today=="Y03_2020"):
        Today = C_2020_March  
    elif(today=="Y04_2020"):
        Today = D_2020_April
    elif(today=="Y05_2020"):
        Today = E_2020_May        
    elif(today=="Y06_2020"):
        Today = F_2020_June       
    elif(today=="Y07_2020"):
        Today = G_2020_July
    elif(today=="Y08_2020"):
        Today = H_2020_August
    elif(today=="Y09_2020"):
        Today = I_2020_September
    elif(today=="Y10_2020"):
        Today = J_2020_October
    elif(today=="Y11_2020"):
        Today = K_2020_November
    elif(today=="Y12_2020"):
        Today = L_2020_December
    elif(today=="Y01_2021"):
        Today = A_2021_January
    elif(today=="Y02_2021"):
        Today = B_2021_February
    elif(today=="Y03_2021"):
        Today = C_2021_March  
    elif(today=="Y04_2021"):
        Today = D_2021_April
    elif(today=="Y05_2021"):
        Today = E_2021_May        
    elif(today=="Y06_2021"):
        Today = F_2021_June       
    elif(today=="Y07_2021"):
        Today = G_2021_July
    elif(today=="Y08_2021"):
        Today = H_2021_August
    elif(today=="Y09_2021"):
        Today = I_2021_September
    elif(today=="Y10_2021"):
        Today = J_2021_October
    elif(today=="Y11_2021"):
        Today = K_2021_November
    elif(today=="Y12_2021"):
        Today = L_2021_December
    elif(today=="Y01_2022"):
        Today = A_2022_January
    elif(today=="Y02_2022"):
        Today = B_2022_February
    elif(today=="Y03_2022"):
        Today = C_2022_March  
    elif(today=="Y04_2022"):
        Today = D_2022_April
    elif(today=="Y05_2022"):
        Today = E_2022_May        
    elif(today=="Y06_2022"):
        Today = F_2022_June       
    elif(today=="Y07_2022"):
        Today = G_2022_July
    elif(today=="Y08_2022"):
        Today = H_2022_August
    elif(today=="Y09_2022"):
        Today = I_2022_September
    elif(today=="Y10_2022"):
        Today = J_2022_October
    elif(today=="Y11_2022"):
        Today = K_2022_November
    elif(today=="Y12_2022"):
        Today = L_2022_December       
       
    calendar = Today.objects.filter(user=u) 
    return render(request, 'calentemp/calendar.html', {'calendars': calendar,
                                                       'today3': today3,
                                                       'click': clickmois})

def calendarprev(request):
    global click    
    click = click-1
    now = datetime.today()+ relativedelta(months=click)
    today = now.strftime("Y%m_%Y")
    u = request.user
    today2 = datetime.today()
    today3 = int(today2.strftime("%d"))
    clickmois = click
    
    if(today=="Y01_2020"):
        Today = A_2020_January
    elif(today=="Y02_2020"):
        Today = B_2020_February
    elif(today=="Y03_2020"):
        Today = C_2020_March  
    elif(today=="Y04_2020"):
        Today = D_2020_April
    elif(today=="Y05_2020"):
        Today = E_2020_May        
    elif(today=="Y06_2020"):
        Today = F_2020_June       
    elif(today=="Y07_2020"):
        Today = G_2020_July
    elif(today=="Y08_2020"):
        Today = H_2020_August
    elif(today=="Y09_2020"):
        Today = I_2020_September
    elif(today=="Y10_2020"):
        Today = J_2020_October
    elif(today=="Y11_2020"):
        Today = K_2020_November
    elif(today=="Y12_2020"):
        Today = L_2020_December
    elif(today=="Y01_2021"):
        Today = A_2021_January
    elif(today=="Y02_2021"):
        Today = B_2021_February
    elif(today=="Y03_2021"):
        Today = C_2021_March  
    elif(today=="Y04_2021"):
        Today = D_2021_April
    elif(today=="Y05_2021"):
        Today = E_2021_May        
    elif(today=="Y06_2021"):
        Today = F_2021_June       
    elif(today=="Y07_2021"):
        Today = G_2021_July
    elif(today=="Y08_2021"):
        Today = H_2021_August
    elif(today=="Y09_2021"):
        Today = I_2021_September
    elif(today=="Y10_2021"):
        Today = J_2021_October
    elif(today=="Y11_2021"):
        Today = K_2021_November
    elif(today=="Y12_2021"):
        Today = L_2021_December
    elif(today=="Y01_2022"):
        Today = A_2022_January
    elif(today=="Y02_2022"):
        Today = B_2022_February
    elif(today=="Y03_2022"):
        Today = C_2022_March  
    elif(today=="Y04_2022"):
        Today = D_2022_April
    elif(today=="Y05_2022"):
        Today = E_2022_May        
    elif(today=="Y06_2022"):
        Today = F_2022_June       
    elif(today=="Y07_2022"):
        Today = G_2022_July
    elif(today=="Y08_2022"):
        Today = H_2022_August
    elif(today=="Y09_2022"):
        Today = I_2022_September
    elif(today=="Y10_2022"):
        Today = J_2022_October
    elif(today=="Y11_2022"):
        Today = K_2022_November
    elif(today=="Y12_2022"):
        Today = L_2022_December       
       
    calendar = Today.objects.filter(user=u) 
    return render(request, 'calentemp/calendar.html', {'calendars': calendar,
                                                       'today3': today3,
                                                       'click': clickmois})

def calendar(request):
    global click    
    click = 0
    now = datetime.today()+ relativedelta(months=click)
    today = now.strftime("Y%m_%Y")
    u = request.user
    today2 = datetime.today()
    today3 = int(today2.strftime("%d"))
    clickmois = click
    
    if(today=="Y01_2020"):
        Today = A_2020_January
    elif(today=="Y02_2020"):
        Today = B_2020_February
    elif(today=="Y03_2020"):
        Today = C_2020_March  
    elif(today=="Y04_2020"):
        Today = D_2020_April
    elif(today=="Y05_2020"):
        Today = E_2020_May        
    elif(today=="Y06_2020"):
        Today = F_2020_June       
    elif(today=="Y07_2020"):
        Today = G_2020_July
    elif(today=="Y08_2020"):
        Today = H_2020_August
    elif(today=="Y09_2020"):
        Today = I_2020_September
    elif(today=="Y10_2020"):
        Today = J_2020_October
    elif(today=="Y11_2020"):
        Today = K_2020_November
    elif(today=="Y12_2020"):
        Today = L_2020_December
    elif(today=="Y01_2021"):
        Today = A_2021_January
    elif(today=="Y02_2021"):
        Today = B_2021_February
    elif(today=="Y03_2021"):
        Today = C_2021_March  
    elif(today=="Y04_2021"):
        Today = D_2021_April
    elif(today=="Y05_2021"):
        Today = E_2021_May        
    elif(today=="Y06_2021"):
        Today = F_2021_June       
    elif(today=="Y07_2021"):
        Today = G_2021_July
    elif(today=="Y08_2021"):
        Today = H_2021_August
    elif(today=="Y09_2021"):
        Today = I_2021_September
    elif(today=="Y10_2021"):
        Today = J_2021_October
    elif(today=="Y11_2021"):
        Today = K_2021_November
    elif(today=="Y12_2021"):
        Today = L_2021_December
    elif(today=="Y01_2022"):
        Today = A_2022_January
    elif(today=="Y02_2022"):
        Today = B_2022_February
    elif(today=="Y03_2022"):
        Today = C_2022_March  
    elif(today=="Y04_2022"):
        Today = D_2022_April
    elif(today=="Y05_2022"):
        Today = E_2022_May        
    elif(today=="Y06_2022"):
        Today = F_2022_June       
    elif(today=="Y07_2022"):
        Today = G_2022_July
    elif(today=="Y08_2022"):
        Today = H_2022_August
    elif(today=="Y09_2022"):
        Today = I_2022_September
    elif(today=="Y10_2022"):
        Today = J_2022_October
    elif(today=="Y11_2022"):
        Today = K_2022_November
    elif(today=="Y12_2022"):
        Today = L_2022_December       
       
    calendar = Today.objects.filter(user=u) 
    return render(request, 'calentemp/calendar.html', {'calendars': calendar,
                                                       'today3': today3,
                                                       'click': clickmois})


def session_list(request, slug):
    global varislug
    global planoftheday
    first = request.user.first_name
    last = request.user.last_name
    varislug = slug
    planoftheday = M_DailyPlan.objects.filter(slugdaily=slug)
    return render(request, 'calentemp/sessions_list.html', {'dailyplans': planoftheday,
                                                            'first': first,
                                                            'last': last})

def exercise_list(request, slug, slugb):
    global varislug2
    global varislug3
    first = request.user.first_name
    last = request.user.last_name    
    u = request.user
    varislug2 = varislug
    varislug3 = slugb   
    if request.method == 'POST':
        form = forms.SaveData(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.title = varislug3
            instance.save()
            messages.info(request, 'Your data has been saved successfully!')
    else:    
        form = forms.SaveData()    
    session = N_Session.objects.filter(slugSess=slugb)

    return render(request, 'calentemp/exercises_list.html', {'sessions': session,
                                                             'form': form,

Calendar/templates/calentemp/home.html
<!DOCTYPE html>

<html>


<head>
    <meta charset="utf-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css"   href="/static/home.css"/>
    <link rel="apple-touch-icon" href="/static/images/logoplanapp2.png" sizes="160x160">
    {% load pwa %}
    {% progressive_web_app_meta %}
    
    <link rel="icon" sizes="160x160" href="/static/images/logoplanapp2.png">

</head>
<body>

    <div class= "container" >
        <div class= "fond">  
            <img src="/static/images/modelfond.png" height="1000px"  />   
        </div>           
        
    </div>
    
    <div class="legend2">
        <div class="styleleg">
        </div>    
    </div>    
        
    <div class="legend">
        <div class= "logout">
            <div class= "backtocalendar">                     
                <h2><a href="{% url 'login:signin' %}">Login</a></h2>                
            </div>
            <div class= "backtocalendar2">                     
                <h2><a href="{% url 'login:signup' %}">Signup</a></h2>                
            </div>  
            <div class= "backtocalendar3">                     
                <h2><a href="{% url 'Calendar:calend' %}">Calendar</a></h2>                
            </div>              
        </div>
        <div class= "logo">  
            <img src="/static/images/logoplanapp3.png" height="147px"  />   
        </div>        
    </div>      
    
</body>
</html>

Calendar/templates/calentemp/sessions_list.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>Daily session</title>
    <link rel="stylesheet" href="/static/sessdet_list.css"/>

</head>


<body>
 
   
    <div class= "container" >
        
        
        <div class= "dailyplan" >
            {% for dailyplan in dailyplans %}
                <div class= "{{ dailyplan.color }}"  >
                    <h1>{{ dailyplan.title }}</h1>
                </div>            
                {% if dailyplan.color1 == "rest" %}            
                    <div class= "{{ dailyplan.color1 }}">
                        <h2><a>{{ dailyplan.session1 }}</a></h2>
                    </div>
                {% else %}
                    <div class= "{{ dailyplan.color1 }}">
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug1 %}">{{ dailyplan.session1 }}</a></h2>
                    </div>                
                {% endif %}
                {% if dailyplan.color2 == "rest" %}            
                    <div class= "{{ dailyplan.color2 }}">
                        <h2><a>{{ dailyplan.session2 }}</a></h2>
                    </div>
                {% else %}                
                    <div class= "{{ dailyplan.color2 }}">                    
                       <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug2 %}">{{ dailyplan.session2 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color3 == "rest" %}            
                    <div class= "{{ dailyplan.color3 }}">
                        <h2><a>{{ dailyplan.session3 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color3 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug3 %}">{{ dailyplan.session3 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color4 == "rest" %}            
                    <div class= "{{ dailyplan.color4 }}">
                        <h2><a>{{ dailyplan.session4 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color4 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug4 %}">{{ dailyplan.session4 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color5 == "rest" %}            
                    <div class= "{{ dailyplan.color5 }}">
                        <h2><a>{{ dailyplan.session5 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color5 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug5 %}">{{ dailyplan.session5 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color6 == "rest" %}            
                    <div class= "{{ dailyplan.color6 }}">
                        <h2><a>{{ dailyplan.session6 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color6 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug6 %}">{{ dailyplan.session6 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color7 == "rest" %}            
                    <div class= "{{ dailyplan.color7 }}">
                        <h2><a>{{ dailyplan.session7 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color7 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug7 %}">{{ dailyplan.session7 }}</a></h2>
                    </div>
                {% endif %}
                {% if dailyplan.color8 == "rest" %}            
                    <div class= "{{ dailyplan.color8 }}">
                        <h2><a>{{ dailyplan.session8 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color8 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug8 %}">{{ dailyplan.session8 }}</a></h2>                
                    </div>
                {% endif %}
                {% if dailyplan.color9 == "rest" %}            
                    <div class= "{{ dailyplan.color9 }}">
                        <h2><a>{{ dailyplan.session9 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color9 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug9 %}">{{ dailyplan.session9 }}</a></h2>                
                    </div>
                {% endif %}
                {% if dailyplan.color10 == "rest" %}            
                    <div class= "{{ dailyplan.color10 }}">
                        <h2><a>{{ dailyplan.session10 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color10 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug10 %}">{{ dailyplan.session10 }}</a></h2>                
                    </div>
                {% endif %}
                {% if dailyplan.color11 == "rest" %}            
                    <div class= "{{ dailyplan.color11 }}">
                        <h2><a>{{ dailyplan.session11 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color11 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug11 %}">{{ dailyplan.session11 }}</a></h2>                
                    </div>
                {% endif %}
                {% if dailyplan.color12 == "rest" %}            
                    <div class= "{{ dailyplan.color12 }}">
                        <h2><a>{{ dailyplan.session12 }}</a></h2>
                    </div>
                {% else %}                        
                    <div class= "{{ dailyplan.color12 }}">                     
                        <h2><a href="{% url 'Calendar:vecro' slug=dailyplan.slugdaily slugb=dailyplan.slug12 %}">{{ dailyplan.session12 }}</a></h2>                
                    </div>                
                {% endif %}                
                
        
            {% endfor %}
        </div>
    </div>
    <div class="legend2">
        <div class="leglabel">Color legend :</div>        
        <div class="styleleg">
            
            <div class="strenleg">Strength</div>        
            <div class="enduleg">Endurance</div>         
            <div class="stableg">Mobility</div>         
            <div class="restleg">Rest</div>

            
        </div>    
    </div>    
        
    <div class="legend">
        {% for dailyplan in dailyplans %}
            <div class= "user" >
                <h1>{{ first }}</h1>
                <h1>{{ last }}</h1>                
            </div>
        {% endfor %}   
        <div class= "logout">                     
            <div class= "backtocalendar">                     
                <h2><a href="{% url 'Calendar:calend' %}">Calendar</a></h2>                
            </div>  
                
        </div>
    <div class= "logo">  
            <a  href="{% url 'Calendar:home' %}">
                <img src="/static/images/logoplanapp3.png" height="147px" />
            </a>    
    </div>         
    
    
</body>
</html>

Calendar/templates/calentemp/testr.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>Daily session</title>


</head>
<body>

    <div class= "dailyplan" >
        {% for dailyplan in m_dailyplan %}
            <div class= "title" >
                <h1>hello</h1>
            </div>     
            
        
        {% endfor %}
    </div>

</body>
</html>
                  'hold2','rep2','weight2','dist2','note2',
                  'hold3','rep3','weight3','dist3','note3',
                  'hold4','rep4','weight4','dist4','note4',                  
                  'hold5','rep5','weight5','dist5','note5',
                  'hold6','rep6','weight6','dist6','note6',
                  'hold7','rep7','weight7','dist7','note7',
                  'hold8','rep8','weight8','dist8','note8',
                  'hold9','rep9','weight9','dist9','note9',
                  'hold10','rep10','weight10','dist10','note10',                  
                  'hold11','rep11','weight11','dist11','note11',
                  'hold12','rep12','weight12','dist12','note12',        